services:
  - type: web
    name: bot-visite-v2
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python render_unified.py
    envVars:
      - key: TELEGRAM_API_ID
        sync: false
      - key: TELEGRAM_API_HASH
        sync: false
      - key: TELEGRAM_PHONE
        sync: false
    healthCheckPath: /status
    healthCheckTimeout: 100
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8080
